---
firstTimeLabels:
  - 1st contribution
firstTimeGreetings: |
  👋 @{user}, seems like this is your first time contribution to {repo}.

  - Please make sure that you have read our [guidelines](#{guideline_url}) and [code of conduct]({coc_url}) before making a contribution.
  - You can comment with `/label Components:[component_name]` to add a label for which component you are working on.
  - You may join our ![Discord](https://img.shields.io/discord/746646622431346728?label=Discord&logo=discord&style=for-the-badge) for staying tuned.
greetings: |
  👋 @{user}, thank you for contributing {repo}.

  - You can comment with `/label Components:[component_name]` to add a label for which component you are working on.
  - You may join our ![Discord](https://img.shields.io/discord/746646622431346728?label=Discord&logo=discord&style=for-the-badge) for staying tuned.
